// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7xGLSQAIgke5JTYdWVdxpTVo3ENiUB_Q',
    appId: '1:1095622271172:web:51de0814cc27371f35a991',
    messagingSenderId: '1095622271172',
    projectId: 'superchat-mad22',
    authDomain: 'superchat-mad22.firebaseapp.com',
    storageBucket: 'superchat-mad22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdK8hVZX0uXpvHOlgEbGaktavp3GKRxN4',
    appId: '1:1095622271172:android:86a803e32a654bd035a991',
    messagingSenderId: '1095622271172',
    projectId: 'superchat-mad22',
    storageBucket: 'superchat-mad22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHsoU4GAE0JiWznKrpqU3VwGABeZIxLEM',
    appId: '1:1095622271172:ios:ce3632f473f67c6a35a991',
    messagingSenderId: '1095622271172',
    projectId: 'superchat-mad22',
    storageBucket: 'superchat-mad22.appspot.com',
    iosClientId:
        '1095622271172-o0hnvacv8v97vrg6o6on5pojggmel85g.apps.googleusercontent.com',
    iosBundleId: 'com.mymobile.superchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHsoU4GAE0JiWznKrpqU3VwGABeZIxLEM',
    appId: '1:1095622271172:ios:ce3632f473f67c6a35a991',
    messagingSenderId: '1095622271172',
    projectId: 'superchat-mad22',
    storageBucket: 'superchat-mad22.appspot.com',
    iosClientId:
        '1095622271172-o0hnvacv8v97vrg6o6on5pojggmel85g.apps.googleusercontent.com',
    iosBundleId: 'com.mymobile.superchat',
  );
}
